language: r
cache: packages

matrix:
  include:
    - os: linux
      r: release
      sudo : false
    - os: linux
      r: devel
      sudo : false
    - os: osx
      latex: false
      r: devel
    - os: osx
      latex: false
      r: release
  allow_failures:
    - os: osx
    
before_install: sudo apt-get install libgdal-dev libproj-dev libgeos-dev libudunits2-dev netcdf-bin
    
addons:
  apt:
    packages:
      - libgdal-dev
      - libproj-dev
      - libudunits2-dev
      - netcdf-bin
      - libmpfr-dev

global:
  - _R_CHECK_FORCE_SUGGESTS_: false