# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

Robust_Stepwise <- function(x, y, correlation_predictors, correlation_response, model_saturation, sig_level, model_size) {
    .Call('_robStepSplitReg_Robust_Stepwise', PACKAGE = 'robStepSplitReg', x, y, correlation_predictors, correlation_response, model_saturation, sig_level, model_size)
}

Robust_Stepwise_Split <- function(x, y, correlation_predictors, correlation_response, model_saturation, sig_level, model_size, n_models) {
    .Call('_robStepSplitReg_Robust_Stepwise_Split', PACKAGE = 'robStepSplitReg', x, y, correlation_predictors, correlation_response, model_saturation, sig_level, model_size, n_models)
}

